// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademico.Persistence.Models;

#nullable disable

namespace SistemaAcademico.Persistence.Migrations
{
    [DbContext(typeof(SistemaAcademicoContext))]
    [Migration("20251228210050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.AreaAcademica", b =>
                {
                    b.Property<string>("AreaAcademicaId")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("AreaAcademica_ID");

                    b.Property<string>("AreaAcademicaNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AreaAcademica_Nombre");

                    b.HasKey("AreaAcademicaId")
                        .HasName("PRIMARY");

                    b.ToTable("AreaAcademica", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Asignatura", b =>
                {
                    b.Property<string>("AsignaturaId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Asignatura_ID");

                    b.Property<string>("IdAreaAcademica")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AsignaturaId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAreaAcademica" }, "FK_Asignatura_AreaAcademica");

                    b.ToTable("Asignatura", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.AsignaturaProgramaAcademico", b =>
                {
                    b.Property<string>("IdAsignatura")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Id_Asignatura");

                    b.Property<int>("IdProgramaAcademico")
                        .HasColumnType("int")
                        .HasColumnName("Id_ProgramaAcademico");

                    b.Property<string>("Corequisito")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("PreRequisitos")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("IdAsignatura", "IdProgramaAcademico")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "Corequisito" }, "FK_AsignaturaProgramaAcademico_Corequisito");

                    b.ToTable("Asignatura_ProgramaAcademico", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Aula", b =>
                {
                    b.Property<int>("IdAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Aula");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAula"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEdificio")
                        .HasColumnType("int")
                        .HasColumnName("ID_Edificio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdAula")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEdificio" }, "FK_Aula_Edificio");

                    b.ToTable("Aula", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Carrera_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarreraId"));

                    b.Property<string>("IdAreaAcademica")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nomenclatura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CarreraId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAreaAcademica" }, "FK_Carrera_AreaAcademica");

                    b.ToTable("Carrera", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.CuentaPorPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRestante")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<decimal>("CantidadTotal")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<bool>("Pagada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuario" }, "FK_CPP_Usuario");

                    b.ToTable("CuentaPorPagar", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("ID_Factura");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFactura" }, "FK_Factura_Detalles");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Edificio", b =>
                {
                    b.Property<int>("IdEdificio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Edificio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEdificio"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nomenclatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdEdificio")
                        .HasName("PRIMARY");

                    b.ToTable("Edificio", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Factura");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<decimal>("Descuento")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("enum('Pagada','Anulada')");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdCuentaPorPagar")
                        .HasColumnType("int")
                        .HasColumnName("ID_CuentaPorPagar");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("IdFactura")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCuentaPorPagar" }, "FK_Factura_CPP");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.PeriodoConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("PreseleccionFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PreseleccionInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SeleccionFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SeleccionInicio")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("PeriodoConfig", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Preseleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("IdAsignatura")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_Asignatura");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Periodo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Preseleccion", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Profesor", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Contratacion");

                    b.Property<string>("GradoAcademico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Grado_Academico");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.ToTable("Profesor", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.ProgramaAcademico", b =>
                {
                    b.Property<int>("ProgramaAcademicoId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramaAcademico_ID");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("ID_Carrera");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TotalCreditos")
                        .HasColumnType("int")
                        .HasColumnName("Total_Creditos");

                    b.Property<int>("TrimestresMaximos")
                        .HasColumnType("int");

                    b.HasKey("ProgramaAcademicoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCarrera" }, "FK_Carrera_ProgramaAcademico");

                    b.ToTable("ProgramaAcademico", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Rol_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RolId")
                        .HasName("PRIMARY");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Seccion", b =>
                {
                    b.Property<int>("SeccionId")
                        .HasColumnType("int")
                        .HasColumnName("Seccion_ID");

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<int>("CupoDisponible")
                        .HasColumnType("int")
                        .HasColumnName("Cupo_Disponible");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("IdAsignatura")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_Asignatura");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int")
                        .HasColumnName("ID_Profesor");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NumeroSeccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Numero_Seccion");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Periodo_Academico");

                    b.HasKey("SeccionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsignatura" }, "FK_Seccion_Asignatura");

                    b.HasIndex(new[] { "IdProfesor" }, "FK_Seccion_Profesor");

                    b.ToTable("Seccion", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.SeccionHorario", b =>
                {
                    b.Property<int>("IdSeccionHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SeccionHorario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSeccionHorario"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdAula")
                        .HasColumnType("int")
                        .HasColumnName("ID_Aula");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Seccion");

                    b.HasKey("IdSeccionHorario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAula" }, "FK_SeccionHorario_Aula");

                    b.HasIndex(new[] { "IdSeccion" }, "FK_SeccionHorario_Seccion");

                    b.ToTable("SeccionHorario", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Seleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("EstatusAcademico")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Periodo");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Seccion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdSeccion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Seleccion", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Tarifario", b =>
                {
                    b.Property<int>("IdTarifario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Tarifario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTarifario"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("enum('Activo','Inactivo')");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("IdTarifario")
                        .HasName("PRIMARY");

                    b.ToTable("Tarifario", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Clave_Hash");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Correo_Institucional");

                    b.Property<string>("CorreoPersonal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Correo_Personal");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Ingreso");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_Rol");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRol" }, "FK_Rol_Usuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioAreaAcademica", b =>
                {
                    b.Property<string>("IdAreaAcademica")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ID_AreaAcademica");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("enum('Activo','Inactivo')");

                    b.HasKey("IdAreaAcademica", "IdUsuario")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdUsuario" }, "CK_UsuarioAreaAcademica1");

                    b.ToTable("Usuario_AreaAcademica", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioProgramaAcademico", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<int>("IdProgramaAcademico")
                        .HasColumnType("int")
                        .HasColumnName("ID_ProgramaAcademico");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("FechaInscripcion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Inscripcion");

                    b.Property<int>("Permanencia")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdProgramaAcademico")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdProgramaAcademico" }, "CK_Usuario_ProgramaAcademico2");

                    b.ToTable("Usuario_ProgramaAcademico", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioRefreshToken", b =>
                {
                    b.Property<int>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_RefreshToken");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRefreshToken"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Expiracion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdRefreshToken")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuario" }, "FK_RefreshToken_Usuario");

                    b.ToTable("Usuario_RefreshToken", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_Rol");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("enum('Activo','Inactivo')");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdRol" }, "CK_UsuarioRol2");

                    b.ToTable("Usuario_Rol", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioTarifario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<int>("IdTarifario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tarifario");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("FechaInscripcion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Inscripcion");

                    b.HasKey("IdUsuario", "IdTarifario")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdTarifario" }, "CK_UsuarioTarifario1");

                    b.ToTable("UsuarioTarifario", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Asignatura", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.AreaAcademica", "IdAreaAcademicaNavigation")
                        .WithMany("Asignaturas")
                        .HasForeignKey("IdAreaAcademica")
                        .IsRequired()
                        .HasConstraintName("FK_Asignatura_AreaAcademica");

                    b.Navigation("IdAreaAcademicaNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.AsignaturaProgramaAcademico", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Asignatura", "CorequisitoNavigation")
                        .WithMany("AsignaturaProgramaAcademicoCorequisitoNavigations")
                        .HasForeignKey("Corequisito")
                        .HasConstraintName("FK_AsignaturaProgramaAcademico_Corequisito");

                    b.HasOne("SistemaAcademico.Persistence.Models.Asignatura", "IdAsignaturaNavigation")
                        .WithMany("AsignaturaProgramaAcademicoIdAsignaturaNavigations")
                        .HasForeignKey("IdAsignatura")
                        .IsRequired()
                        .HasConstraintName("CK_AsignaturaProgramaAcademico1");

                    b.Navigation("CorequisitoNavigation");

                    b.Navigation("IdAsignaturaNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Aula", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Edificio", "IdEdificioNavigation")
                        .WithMany("Aulas")
                        .HasForeignKey("IdEdificio")
                        .IsRequired()
                        .HasConstraintName("FK_Aula_Edificio");

                    b.Navigation("IdEdificioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Carrera", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.AreaAcademica", "IdAreaAcademicaNavigation")
                        .WithMany("Carreras")
                        .HasForeignKey("IdAreaAcademica")
                        .IsRequired()
                        .HasConstraintName("FK_Carrera_AreaAcademica");

                    b.Navigation("IdAreaAcademicaNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.CuentaPorPagar", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("CuentaPorPagars")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_CPP_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.DetalleFactura", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Factura", "IdFacturaNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdFactura")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Detalles");

                    b.Navigation("IdFacturaNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Factura", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.CuentaPorPagar", "IdCuentaPorPagarNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCuentaPorPagar")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_CPP");

                    b.Navigation("IdCuentaPorPagarNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Preseleccion", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Asignatura", "IdAsignaturaNavigation")
                        .WithMany("Preseleccions")
                        .HasForeignKey("IdAsignatura")
                        .IsRequired()
                        .HasConstraintName("FK_Preseleccion_Asignatura");

                    b.HasOne("SistemaAcademico.Persistence.Models.PeriodoConfig", "IdPeriodoNavigation")
                        .WithMany("Preseleccions")
                        .HasForeignKey("IdPeriodo")
                        .IsRequired()
                        .HasConstraintName("FK_Preseleccion_Periodo");

                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Preseleccions")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Preseleccion_Usuario");

                    b.Navigation("IdAsignaturaNavigation");

                    b.Navigation("IdPeriodoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Profesor", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("Profesor")
                        .HasForeignKey("SistemaAcademico.Persistence.Models.Profesor", "IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Profesor_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.ProgramaAcademico", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Carrera", "IdCarreraNavigation")
                        .WithMany("ProgramaAcademicos")
                        .HasForeignKey("IdCarrera")
                        .IsRequired()
                        .HasConstraintName("FK_Carrera_ProgramaAcademico");

                    b.Navigation("IdCarreraNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Seccion", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Asignatura", "IdAsignaturaNavigation")
                        .WithMany("Seccions")
                        .HasForeignKey("IdAsignatura")
                        .IsRequired()
                        .HasConstraintName("FK_Seccion_Asignatura");

                    b.HasOne("SistemaAcademico.Persistence.Models.Profesor", "IdProfesorNavigation")
                        .WithMany("Seccions")
                        .HasForeignKey("IdProfesor")
                        .IsRequired()
                        .HasConstraintName("FK_Seccion_Profesor");

                    b.Navigation("IdAsignaturaNavigation");

                    b.Navigation("IdProfesorNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.SeccionHorario", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Aula", "IdAulaNavigation")
                        .WithMany("SeccionHorarios")
                        .HasForeignKey("IdAula")
                        .IsRequired()
                        .HasConstraintName("FK_SeccionHorario_Aula");

                    b.HasOne("SistemaAcademico.Persistence.Models.Seccion", "IdSeccionNavigation")
                        .WithMany("SeccionHorarios")
                        .HasForeignKey("IdSeccion")
                        .IsRequired()
                        .HasConstraintName("FK_SeccionHorario_Seccion");

                    b.Navigation("IdAulaNavigation");

                    b.Navigation("IdSeccionNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Seleccion", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.PeriodoConfig", "IdPeriodoNavigation")
                        .WithMany("Seleccions")
                        .HasForeignKey("IdPeriodo")
                        .IsRequired()
                        .HasConstraintName("FK_Seleccion_Periodo");

                    b.HasOne("SistemaAcademico.Persistence.Models.Seccion", "IdSeccionNavigation")
                        .WithMany("Seleccions")
                        .HasForeignKey("IdSeccion")
                        .IsRequired()
                        .HasConstraintName("FK_Seleccion_Seccion");

                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Seleccions")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Seleccion_Usuario");

                    b.Navigation("IdPeriodoNavigation");

                    b.Navigation("IdSeccionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Usuario", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Rol_Usuario");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioAreaAcademica", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.AreaAcademica", "IdAreaAcademicaNavigation")
                        .WithMany("UsuarioAreaAcademicas")
                        .HasForeignKey("IdAreaAcademica")
                        .IsRequired()
                        .HasConstraintName("CK_UsuarioAreaAcademica2");

                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioAreaAcademicas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("CK_UsuarioAreaAcademica1");

                    b.Navigation("IdAreaAcademicaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioProgramaAcademico", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.ProgramaAcademico", "IdProgramaAcademicoNavigation")
                        .WithMany("UsuarioProgramaAcademicos")
                        .HasForeignKey("IdProgramaAcademico")
                        .IsRequired()
                        .HasConstraintName("CK_Usuario_ProgramaAcademico2");

                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioProgramaAcademicos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("CK_Usuario_ProgramaAcademico1");

                    b.Navigation("IdProgramaAcademicoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioRefreshToken", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioRefreshTokens")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioRol", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Rol", "IdRolNavigation")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("CK_UsuarioRol2");

                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("CK_UsuarioRol1");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.UsuarioTarifario", b =>
                {
                    b.HasOne("SistemaAcademico.Persistence.Models.Tarifario", "IdTarifarioNavigation")
                        .WithMany("UsuarioTarifarios")
                        .HasForeignKey("IdTarifario")
                        .IsRequired()
                        .HasConstraintName("CK_UsuarioTarifario1");

                    b.HasOne("SistemaAcademico.Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioTarifarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("CK_UsuarioTarifario2");

                    b.Navigation("IdTarifarioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.AreaAcademica", b =>
                {
                    b.Navigation("Asignaturas");

                    b.Navigation("Carreras");

                    b.Navigation("UsuarioAreaAcademicas");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Asignatura", b =>
                {
                    b.Navigation("AsignaturaProgramaAcademicoCorequisitoNavigations");

                    b.Navigation("AsignaturaProgramaAcademicoIdAsignaturaNavigations");

                    b.Navigation("Preseleccions");

                    b.Navigation("Seccions");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Aula", b =>
                {
                    b.Navigation("SeccionHorarios");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Carrera", b =>
                {
                    b.Navigation("ProgramaAcademicos");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.CuentaPorPagar", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Edificio", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.PeriodoConfig", b =>
                {
                    b.Navigation("Preseleccions");

                    b.Navigation("Seleccions");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Profesor", b =>
                {
                    b.Navigation("Seccions");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.ProgramaAcademico", b =>
                {
                    b.Navigation("UsuarioProgramaAcademicos");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRols");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Seccion", b =>
                {
                    b.Navigation("SeccionHorarios");

                    b.Navigation("Seleccions");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Tarifario", b =>
                {
                    b.Navigation("UsuarioTarifarios");
                });

            modelBuilder.Entity("SistemaAcademico.Persistence.Models.Usuario", b =>
                {
                    b.Navigation("CuentaPorPagars");

                    b.Navigation("Preseleccions");

                    b.Navigation("Profesor");

                    b.Navigation("Seleccions");

                    b.Navigation("UsuarioAreaAcademicas");

                    b.Navigation("UsuarioProgramaAcademicos");

                    b.Navigation("UsuarioRefreshTokens");

                    b.Navigation("UsuarioRols");

                    b.Navigation("UsuarioTarifarios");
                });
#pragma warning restore 612, 618
        }
    }
}
